total_size = 0 # in bytes
start_up_time_us = 0 # time to wait before communicating with the device after power up

# Three responses to JEDEC command 0x9f. Used to detect the device
manufacturer_id = 0
memory_type = 0
capacity = 0

# Max clock speed for all operations and the fastest read mode. May not be
# achievable on a particular board.
max_clock_speed_mhz = 0

# Bitmask for Quad Enable bit if present. 0x00 otherwise. This is for the first byte in the status
# register when single_status_byte = true, and the second status byte when false.
quad_enable_bit_mask = 0x0

# Supports the 0x0b fast read command with 8 dummy cycles.
has_sector_protection = false

# Supports the fast read, quad output command 0x6b with 8 dummy cycles.
supports_fast_read = false

# Supports the quad input page program command 0x32. This is known as 1-1-4 because it only
# uses all four lines for data.
supports_qspi = false

supports_qspi_writes = false

# Requires a separate command 0x31 to write to the second byte of the status register.
# Otherwise two bytes are written via 0x01.
write_status_register_split = false

# Status byte number that contains the quad enable bit. (1-based to match flash docs)
quad_enable_status_byte = 1

# Does not support using a ready bit within the status register
no_ready_bit = false

# Does not support the erase command (0x20)
no_erase_cmd = false

# Device does not have a reset command
no_reset_cmd = false
