# Settings for the Cypress (was Spansion) S25FL128L 16MB SPI flash.
# Datasheet: https://www.infineon.com/dgdl/Infineon-S25FL256L_S25FL128L_256-MB_(32-MB)_128-MB_(16-MB)_3.0_V_FL-L_FLASH_MEMORY-DataSheet-v09_00-EN.pdf?fileId=8ac78c8c7d0d8da4017d0ed40e335224
total_size = 0x1600000 # 16 MiB
start_up_time_us = 300
memory_type = 0x60
capacity = 0x18
max_clock_speed_mhz = 133
6b_quad_read = true
32_qspi_write = true