// Settings for the Macronix MX25L1606 2MiB SPI flash.
// Datasheet:
#define MX25L1606  {\
    .total_size = (1 << 21), /* 2 MiB */ \
    .start_up_time_us = 5000, \
    .manufacturer_id = 0xc2, \
    .memory_type = 0x20, \
    .capacity = 0x15, \
    .max_clock_speed_mhz = 8, \
    .quad_enable_bit_mask = 0x40, \
    .has_sector_protection = false, \
    .supports_fast_read = true, \
    .supports_qspi = true, \
    .supports_qspi_writes = true, \
    .write_status_register_split = false, \
    .single_status_byte = true, \
}
