start_up_time_us = 10000
manufacturer_id = 0x1f
max_clock_speed_mhz = 85
quad_enable_bit_mask = 0x00
supports_qspi = false
supports_qspi_writes = false
write_status_register_split = false
single_status_byte = false
