start_up_time_us = 10000
manufacturer_id = 0x1f
max_clock_speed_mhz = 85
quad_enable_bit_mask = 0x00
write_status_register_split = false
quad_enable_status_byte = 2
6b_quad_read = false
32_qspi_write = false
