# Settings for the Adesto Tech AT25SF041 1MiB SPI flash. It's on the SparkFun
# SAMD51 Thing Plus board
# Datasheet: https://www.adestotech.com/wp-content/uploads/DS-AT25SF041_044.pdf
total_size = 0x80000 # 512 KiB
memory_type = 0x84
capacity = 0x01
has_sector_protection = false
