# Settings for the Adesto Tech AT25SF161-SSHD-T 2MiB SPI flash
# for the StringCar M0 (SAMD21) Express board.
# Source: https://www.digikey.com/product-detail/en/adesto-technologies/AT25SF161-SDHD-T/1265-1230-1-ND/
# Datasheet: https://www.adestotech.com/wpo-content/uploads/jDS-AT25SF161_046.pdf
total_size = 0x200000 # 2 MiB
memory_type = 0x86
capacity = 0x01
has_sector_protection = true
